### ISSUE TITLE
html5lib

### ISSUE THREAD

**Issue by syfluqs** [swapagarwal/JARVIS-on-Messenger#161]
Upon running jarvis.py the following error was found

```
Traceback (most recent call last):
  File "jarvis.py", line 6, in <module>
    import modules
  File "/home/roy/Downloads/JARVIS-on-Messenger/modules/__init__.py", line 6, in <module>
    from src import *
  File "/home/roy/Downloads/JARVIS-on-Messenger/modules/src/wiki.py", line 2, in <module>
    import wikipedia
  File "/usr/lib/python2.7/site-packages/wikipedia/__init__.py", line 1, in <module>
    from .wikipedia import *
  File "/usr/lib/python2.7/site-packages/wikipedia/wikipedia.py", line 5, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

```

**Comment by dranknight09** [comment]
Try...
pip2 install html5lib==0.9999999

**Comment by syfluqs** [comment]
Thanks, it worked! Maybe the requirements.txt should have an entry for html5lib.

**Comment by swapagarwal** [comment]
Thanks @dranknight09! Would you know why others are not facing this issue?
